// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icurpcximejqtspshdvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljdXJwY3hpbWVqcXRzcHNoZHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDcwNzcsImV4cCI6MjA2NTc4MzA3N30.ZPc8oU-vRAnd1WlqmdIXB8RScbWvKf3HA_68nh2xQrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);